### ISSUE TITLE
Highlight just changed characters, not lines. 

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [ymattw/ydiff#104]
Please just highlight changed characters, not lines. This can be done by parsing the output of:
```
git diff --word-diff-regex=.
```
See here: https://stackoverflow.com/questions/3231759/how-can-i-visualize-per-character-differences-in-a-unified-diff-file/7870727#7870727

You may also need:
```
git diff --word-diff-regex='[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+'
```

This is how `meld` gets their char-by-char highlighting information I'm pretty sure, as I just did a cross-comparison and the output from either of those two commands above seems to match nearly perfectly. 

If you add char-by-char highlighting, your tool would be _much_ closer to `meld` and _much_ more functional and useful. 

In case someone else is able to add this support, please also drop in some notes here to orient us to your code so we would know _where_ these parsing changes would need to be added. 

Also, can you please explain your tool?:

1. When is text _colored_, and what colors mean what?
    1. Where is this in your code?
2. When is text _highlighted_, and what colors mean what?
    1. Where is this in your code?
3. When is text _underlined_, and what means what?
    1. Where is this in your code?

I see some fantastic opportunities for beautification here. Again, I really think this could be made to look _very similar_ to `meld`, which would be _awesome_!

**Comment by ymattw** [comment]
difflib may treats two texts full line changes or partial changes, one example is `import foo` vs `import bar` will be treated full line change instead of only `foo` changed to `bar`. I also noticed the undesired behavior, which confused me for a long time. Didn't want to dig it out until recently I found the hardcoded "similarity ratio" threshold [0.74999](https://github.com/python/cpython/blob/6293d00e7201f3f28b1f4512e57dc4f03855cabd/Lib/difflib.py#L919).

I did some experiments, and IMHO highlight every changed characters can make the result too verbose to read. I've decided to only highlight at word level - similar to `git diff --word-diff` but words are split with camel cased and snaked cased variable names taken into account. I don't think users every need to customize that rule.

Check out the latest version! See also details in [split_to_words()](https://github.com/ymattw/ydiff/blob/59827f14d99e053bb7f34b38ee1ae71effbb5917/ydiff.py#L168).
