### ISSUE TITLE
ydiff 1.4.1 - calling markup_to_pager got AttributeError: type object 'opts' has no attribute 'theme'

### ISSUE THREAD

**Issue by askarfc** [ymattw/ydiff#124]
We set up a Patroni cluster and encountered an issue with the latest version, Patroni 4.0.3, which installs ydiff version 1.4 by default. When running the command patronictl -c /etc/patroni.yml edit-config to modify the shared PostgreSQL configuration, we received an error:

patronictl -c /etc/patroni.yml edit-config
Traceback (most recent call last):
  File "/usr/local/bin/patronictl", line 8, in <module>
    sys.exit(ctl())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/patroni/ctl.py", line 2122, in edit_config
    show_diff(before_editing, after_editing)
  File "/usr/local/lib/python3.10/dist-packages/patroni/ctl.py", line 1917, in show_diff
    markup_to_pager(PatchStream(buf), opts)
  File "/usr/local/lib/python3.10/dist-packages/ydiff.py", line 640, in markup_to_pager
    theme=opts.theme)
AttributeError: type object 'opts' has no attribute 'theme'

**The solution was to downgrade ydiff to version 1.3, which resolved the issue.**

**Comment by ymattw** [comment]
> markup_to_pager(PatchStream(buf), opts)

Looks like you are using ydiff as a library, this is never promised as an API (see also #117).

A quick fix on you own side is to `setattr(opts, 'theme', default)`. Also please note ydiff default CLI options may change over time: `-s/--side_by_side` becomes default in version 1.4 because it is the most useful feature (vs. `-u/--unified`).

You will also want to restrict the dependency declaration. I can only maintain the same behavior across patch revisions (major.minor.*patch*).

On my side, I will change the fingerprint of markup_to_pager() to take keyed parameters instead of taking an `opts` object.

**Comment by askarfc** [comment]
Thank you very much for the quick response

> > markup_to_pager(PatchStream(buf), opts)
> 
> Looks like you are using ydiff as a library, this is never promised as an API (see also #117).
> 
> A quick fix on you own side is to `setattr(opts, 'theme', default)`. Also please note ydiff default CLI options may change over time: `-s/--side_by_side` becomes default in version 1.4 because it is the most useful feature (vs. `-u/--unified`).
> 
> You will also want to restrict the dependency declaration. I can only maintain the same behavior across patch revisions (major.minor._patch_).
> 
> On my side, I will change the fingerprint of markup_to_pager() to take keyed parameters instead of taking an `opts` object.

Thank you very much for the quick response

**Comment by ymattw** [comment]
I believe [this](https://github.com/patroni/patroni/blob/4ce0f99cfb5b08bf770a935c59936a6353e3d27d/patroni/ctl.py#L1924) is your code suffered by the ydiff upgrade.

I recommend rewritting the logic to just pipe the result from `difflib.unified_diff()` to CLI program `ydiff` instead of calling `ydiff.markup_to_pager()`. Something like:

```
p = subprocess.Popen(['ydiff', '--unified`], stdin=subprocess.PIPE, text=True)
p.communicate(input=''.join(unified_diff))
if p.returncode != 0:
    # error handling
```

**Comment by ymattw** [comment]
@askarfc Could you give me feedback about above idea of piping the result from `difflib.unified_diff()` to CLI program `ydiff` instead?  I really do not want to break people unintentionally, the best would be making internal symbols protected, once you migrated away from the last public function `markup_to_pager`. Thanks.

**Comment by ymattw** [comment]
Now tracked as https://github.com/patroni/patroni/issues/3218.  markup_to_pager will be made private once that is solved.
